name: Publish Package to registry
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        name: Install pnpm

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - run: pnpm publish --filter "@marklai/shared-config-biome" --access public --no-git-checks
        if: ${{ steps.release.outputs['packages/biome--release_created'] }}

      - run: pnpm publish --filter "@marklai/shared-config-typescript" --access public --no-git-checks
        if: ${{ steps.release.outputs['packages/typescript--release_created'] }}

      - run: pnpm publish --filter "@marklai/shared-config-commitlint" --access public --no-git-checks
        if: ${{ steps.release.outputs['packages/commitlint--release_created'] }}
